DELETE http://localhost:3001/api/persons/404
###
POST http://localhost:3001/api/persons  HTTP/1.1
content-type: application/json


{
    "name":"zz",
    "number":"123"
}



# npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"